import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { api } from '../../lib/api';
import { AdminPage } from '../../components/ui/AdminPage';

type Product = { id: number; nom: string; description: string; categorie: string; prix_gnf: number; image_url?: string; disponible: boolean };
type Order = { id: number; reference: string; nom_client: string; telephone: string; quartier: string; ville: string; total_gnf: number; acompte_gnf: number; reste_gnf: number; statut: string; statut_paiement: string; };
const orderStatuses = ['en_attente', 'confirmee', 'en_preparation', 'en_livraison', 'livree', 'annulee'];
const paymentStatuses = ['a_payer', 'en_attente', 'partiel', 'paye', 'echec'];
const money = (value: number) => `${new Intl.NumberFormat('fr-FR').format(value)} GNF`;

export default function RestaurationManager() {
  const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<Product | null>(null); const [modalOpen, setModalOpen] = useState(false); const [form, setForm] = useState({ nom: '', description: '', categorie: 'plats', prix_gnf: '', image: null as File | null, disponible: true });
  const load = async () => { const [menu, command] = await Promise.all([api.get('/api/v1/admin/restauration/menu'), api.get('/api/v1/admin/restauration/commandes')]); setProducts(menu.data.data || []); setOrders(command.data.data || []); setLoading(false); };
  useEffect(() => { load().catch(() => setLoading(false)); }, []);
  const open = (product?: Product) => { setEditing(product || null); setForm({ nom: product?.nom || '', description: product?.description || '', categorie: product?.categorie || 'plats', prix_gnf: product ? String(product.prix_gnf) : '', image: null, disponible: product?.disponible ?? true }); setModalOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const data = new FormData(); data.append('nom', form.nom); data.append('description', form.description); data.append('categorie', form.categorie); data.append('prix_gnf', form.prix_gnf); data.append('disponible', String(form.disponible)); if (form.image) data.append('image', form.image); if (editing) await api.put(`/api/v1/admin/restauration/menu/${editing.id}`, data); else await api.post('/api/v1/admin/restauration/menu', data); setEditing(null); setModalOpen(false); await load(); };
  const updateOrder = async (id: number, field: 'statut' | 'statut_paiement', value: string) => { await api.put(`/api/v1/admin/restauration/commandes/${id}/${field === 'statut' ? 'statut' : 'paiement'}`, { [field]: value }); await load(); };
  return <AdminPage loading={loading}><div className="space-y-10 text-slate-200"><div className="flex justify-between items-center"><div><h2 className="text-2xl font-bold">Menu & commandes SEBA</h2><p className="text-slate-400 text-sm mt-1">Prix, disponibilité, livraison et suivi opérationnel.</p></div><button onClick={() => open()} className="flex items-center gap-2 bg-amber-600 px-4 py-2 rounded-lg"><Plus size={16} /> Nouveau plat</button></div>
    <section className="bg-[#1e293b] border border-slate-700 rounded-lg overflow-hidden"><div className="p-5 border-b border-slate-700"><h3 className="font-semibold">Produits du menu</h3></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-800/50 text-slate-400"><tr><th className="p-4 text-left">Nom</th><th className="p-4 text-left">Catégorie</th><th className="p-4 text-left">Prix</th><th className="p-4 text-left">Disponible</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-700">{products.map((product) => <tr key={product.id}><td className="p-4">{product.nom}</td><td className="p-4">{product.categorie}</td><td className="p-4">{money(product.prix_gnf)}</td><td className="p-4">{product.disponible ? 'Oui' : 'Non'}</td><td className="p-4 text-right"><button title="Modifier" onClick={() => open(product)} className="mr-3 text-amber-400"><Pencil size={16} /></button><button title="Supprimer" onClick={async () => { if (confirm('Supprimer ce plat ?')) { await api.delete(`/api/v1/admin/restauration/menu/${product.id}`); await load(); } }} className="text-red-400"><Trash2 size={16} /></button></td></tr>)}</tbody></table></div></section>
    <section className="bg-[#1e293b] border border-slate-700 rounded-lg overflow-hidden"><div className="p-5 border-b border-slate-700"><h3 className="font-semibold">Commandes reçues</h3></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-800/50 text-slate-400"><tr><th className="p-4 text-left">Commande / client</th><th className="p-4 text-left">Livraison</th><th className="p-4 text-left">Total</th><th className="p-4 text-left">Commande</th><th className="p-4 text-left">Paiement</th></tr></thead><tbody className="divide-y divide-slate-700">{orders.map((order) => <tr key={order.id}><td className="p-4"><strong>{order.reference}</strong><br />{order.nom_client}<br /><span className="text-slate-400">{order.telephone}</span></td><td className="p-4">{order.quartier}, {order.ville}</td><td className="p-4">{money(order.total_gnf)}<br /><span className="text-xs text-slate-400">Acompte {money(order.acompte_gnf)} / reste {money(order.reste_gnf)}</span></td><td className="p-4"><select value={order.statut} onChange={(e) => updateOrder(order.id, 'statut', e.target.value)} className="bg-slate-800 border border-slate-600 p-2 rounded">{orderStatuses.map((status) => <option key={status}>{status}</option>)}</select></td><td className="p-4"><select value={order.statut_paiement} onChange={(e) => updateOrder(order.id, 'statut_paiement', e.target.value)} className="bg-slate-800 border border-slate-600 p-2 rounded">{paymentStatuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></section>
    {modalOpen ? <div className="fixed inset-0 bg-black/60 flex items-center justify-center p-4 z-50"><form onSubmit={save} className="bg-[#1e293b] border border-slate-700 p-6 rounded-lg w-full max-w-lg space-y-4"><h3 className="text-xl font-semibold">{editing ? 'Modifier le plat' : 'Nouveau plat'}</h3><input required placeholder="Nom" value={form.nom} onChange={(e) => setForm({ ...form, nom: e.target.value })} className="w-full bg-slate-800 border border-slate-600 p-3 rounded" /><textarea placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="w-full bg-slate-800 border border-slate-600 p-3 rounded" /><div className="grid grid-cols-2 gap-3"><select value={form.categorie} onChange={(e) => setForm({ ...form, categorie: e.target.value })} className="bg-slate-800 border border-slate-600 p-3 rounded"><option value="boulangerie">Boulangerie</option><option value="plats">Plats</option><option value="boissons">Boissons</option></select><input required type="number" min="0" placeholder="Prix GNF" value={form.prix_gnf} onChange={(e) => setForm({ ...form, prix_gnf: e.target.value })} className="bg-slate-800 border border-slate-600 p-3 rounded" /></div><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(e) => setForm({ ...form, image: e.target.files?.[0] || null })} /><label className="flex gap-2"><input type="checkbox" checked={form.disponible} onChange={(e) => setForm({ ...form, disponible: e.target.checked })} /> Disponible</label><div className="flex justify-end gap-3"><button type="button" onClick={() => { setEditing(null); setModalOpen(false); }} className="px-4 py-2">Annuler</button><button className="bg-amber-600 px-4 py-2 rounded">Enregistrer</button></div></form></div> : null}</div></AdminPage>;
}
